### ISSUE TITLE
Create circuit diagram through circuit-diagram.org

### ISSUE THREAD

**Issue by BentleySettin** [TinyCamML/Boron-and-OpenMV-Basics#2]

**Comment by BentleySettin** [comment]
Remove Featherwing.

**Comment by BentleySettin** [comment]
Most updated one [here](https://github.com/TinyCamML/Boron-and-OpenMV/commit/7f354bfe6cdb0ece5d962a43f67b06334efba856)

**Comment by BentleySettin** [comment]
reopening for updates. 

@SUPScientist I am updating the circuit diagram to hopefully its final product. On the Circuit diagram website there is no solar panel plus battery symbol so I just used a battery symbol. I attached an image because the attached battery is not very... subtle. Is there another way you recommend displaying this? 



![Image](https://github.com/TinyCamML/Boron-and-OpenMV-Basics/assets/112282611/2f98a03a-f8cd-484e-8886-2decda071092)

**Comment by SUPScientist** [comment]
> reopening for updates.

This would be better as a new issue in the repository that the issue pertains to (just like the other recent issue). It's technically a new issue since the new electrical design corresponds to the new overall system design (e.g., including new firmware, etc.). 

> Is there another way you recommend displaying this?

I'd recommend showing a single 5V supply going into VUSB on the Boron and also branching off into VIN on the OpenMV. Even though the VUSB input to the Boron is via a separate connector on the physical Boron device, from an electrical diagram standpoint, the function is the same whether it goes into the VUSB pin on the header pin or the micro-USB connector (you can prove this to yourself by checking for connectivity with the multimeter). 

For representing the solar charging component, maybe just add a simple icon (box is fine) upstream of the +5V symbol for the 5V battery and add a solar panel label.

**Comment by SUPScientist** [comment]
As mentioned above, this wiring diagram issue more accurately belongs in a different repository. Closing here and opening as https://github.com/TinyCamML/Boron-and-OpenMV/issues/12 in that repo.
